epochs: 5
learning_rate: 0.01
batch_size: 8
checkpoint_path: "model_checkpoints/model_checkpoint.pth"
register_model: false
# loss_function: "CrossEntropyLoss"
# metric_function: "Accuracy"
# optimizer: "SGD"
